// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/chargers": {
            "post": {
                "description": "Creates a new charger with the given name and timezone. See /v1/timezones for a list of valid timezones.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chargers"
                ],
                "summary": "Create a new charger",
                "parameters": [
                    {
                        "description": "Charger object",
                        "name": "charger",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ChargerInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Charger"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/chargers/bulk-schedule": {
            "post": {
                "description": "Links multiple chargers to a specific pricing schedule in one request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chargers"
                ],
                "summary": "Assign a schedule to multiple chargers",
                "parameters": [
                    {
                        "description": "Bulk assignment object",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BulkScheduleInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/chargers/{id}/price": {
            "get": {
                "description": "Returns the price per kWh for a given charger and timestamp. Defaults to now in UTC if no timestamp provided.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chargers"
                ],
                "summary": "Get price for a charger at a specific time",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Charger ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Timestamp in RFC3339 format (e.g. 2024-05-10T15:00:00Z)",
                        "name": "timestamp",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PriceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/chargers/{id}/schedule": {
            "post": {
                "description": "Links a charger to a specific pricing schedule.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chargers"
                ],
                "summary": "Assign a schedule to a charger",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Charger ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Schedule ID (e.g. {'schedule_id': 1})",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/schedules": {
            "get": {
                "description": "Returns a list of all available pricing schedules.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "List all schedules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Schedule"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new schedule with a list of intervals.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Create a pricing schedule",
                "parameters": [
                    {
                        "description": "Schedule object",
                        "name": "schedule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ScheduleInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Schedule"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/schedules/{id}": {
            "put": {
                "description": "Updates the name, description, and intervals of an existing schedule.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Update a schedule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Schedule object",
                        "name": "schedule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ScheduleInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Schedule"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/timezones": {
            "get": {
                "description": "Returns a list of common valid timezones that can be used when creating a charger.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chargers"
                ],
                "summary": "List common valid timezones",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.BulkScheduleInput": {
            "type": "object",
            "required": [
                "charger_ids",
                "schedule_id"
            ],
            "properties": {
                "charger_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "schedule_id": {
                    "type": "integer"
                }
            }
        },
        "models.Charger": {
            "type": "object",
            "properties": {
                "created_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "models.ChargerInput": {
            "type": "object",
            "required": [
                "name",
                "timezone"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "models.Interval": {
            "type": "object",
            "properties": {
                "days_of_week": {
                    "type": "integer"
                },
                "end_time": {
                    "description": "HH:MM:SS",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "price_per_kwh": {
                    "type": "number"
                },
                "start_time": {
                    "description": "HH:MM:SS",
                    "type": "string"
                }
            }
        },
        "models.IntervalInput": {
            "type": "object",
            "required": [
                "days_of_week",
                "end_time",
                "price_per_kwh",
                "start_time"
            ],
            "properties": {
                "days_of_week": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "price_per_kwh": {
                    "type": "number"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "models.PriceResponse": {
            "type": "object",
            "properties": {
                "charger_id": {
                    "type": "integer"
                },
                "currency": {
                    "type": "string"
                },
                "price_per_kwh": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.Schedule": {
            "type": "object",
            "properties": {
                "created_date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "intervals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Interval"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.ScheduleInput": {
            "type": "object",
            "required": [
                "intervals",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "intervals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IntervalInput"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8071",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "EV Charger TOU Pricing API",
	Description:      "A backend service for managing Time-of-Use (TOU) pricing for EV chargers.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
